### ISSUE TITLE
[Bug]: When a user changes the language on scratchpad, propagate to all shared sessions along with the code.

### ISSUE THREAD

**Issue by SuhailAhmedVelorum** [learninbit-project/issues#5]
### What kind of bug is this?

Functional

### Which component is affected?

Scratchpad

### What should have happened?

When a user changes the language on a scratchpad make sure that any other users using the same scratchpad also see the language change. Maybe even a notification. We should also relook at our code being switched on language change. Default code makes sense only until the point that the user starts writing code.

### What is actually happening?

The language changes on the primary scratchpad instance but not on shared ones. The code does change though.

### What action triggered it?

Language change in the scratchpad editor

### Level of Impact

9

### Since when has this been occurring?

7 July

**Comment by UdaySagar-Git** [comment]
This is no longer valid , since we are now limitting scratchpad to one language
